name: CI
on:
  pull_request:
    branches:
      - main
  branches:
    - formatter-ci
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.101'
      - name: Run Fantomas and check for changes
        run: dotnet fantomas --check .
